image: php:8.3-cli

variables:
  DB_USER: runner
  DB_PASSWORD: password
  DB_HOST: mysql
  DB_PORT: 3306
  DB_NAME: phpunit
  DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=8.0.32&charset=utf8mb4"

services:
  - name: mysql:8.0
    alias: mysql
    variables:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: root

stages:
  - build
  - test
  - push_preprod
  - deploy_preprod
  - push_prod
  - deploy_prod

cache:
  paths:
    - vendor/
    - ~/.composer/cache

.php_setup: &php_setup
  before_script:
      - apt-get update && apt-get install -y curl git unzip zip libzip-dev zlib1g-dev default-mysql-client
      - docker-php-ext-install zip pdo pdo_mysql
      - pecl install xdebug && docker-php-ext-enable xdebug
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - php -m | grep -E 'xml|mbstring'
      - apt-get install -y lftp

build:
  <<: *php_setup
  stage: build
  script:
    - echo "Build en cours..."
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction
    - php bin/console importmap:install
    - php bin/console asset:install

    - php bin/console doctrine:database:create --if-not-exists
    - php bin/console doctrine:migrations:migrate --no-interaction

    - php -S 127.0.0.1:8000 -t public > server.log 2>&1 &
    - until curl -s http://127.0.0.1:8000; do echo "Waiting for Symfony server..."; sleep 5; done
  when: on_success
  only:
   - dev

test:
  <<: *php_setup
  stage: test
  variables:
    XDEBUG_MODE: coverage
  needs:
    - job: build
  script:
    - echo "Test en cours..."
    - php bin/console importmap:install
    - mysql -h "$DB_HOST" -u root -proot -e "DROP USER IF EXISTS '$DB_USER'@'%';"
    - mysql -h "$DB_HOST" -u root -proot -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';"
    - mysql -h "$DB_HOST" -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'%';"
    - mysql -h "$DB_HOST" -u root -proot -e "FLUSH PRIVILEGES;"
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:migrations:migrate --no-interaction --env=test
    - composer grumphp
  when: on_success
  only:
    - dev

push_preprod:
  image: alpine:latest
  stage: push_preprod
  before_script:
    - apk add --no-cache git
  script:
    - echo "Push en cours..."
    - |
      cat <<- EOF > .gitignore
      .editor-config
      *.xml
      *.lock
      *.disabled
      grumphp.yml
      src/tests

      /.env.local
      /.env.local.php
      /.env.*.local
      /config/secrets/prod/prod.decrypt.private.php
      /config/secrets/dev/dev.decrypt.private.php
      /public/bundles/
      /var/
      /vendor/
      /phpunit.xml
      .phpunit.result.cache
      .phpunit.result.cache
      /phpunit.xml
      /public/assets/
      /assets/vendor/

      EOF

    - git config --global user.name "CI-CD Robot"
    - git config --global user.email "robot.gertrude@gmail.com"

    - git init
    - git add .gitignore
    - git commit -m"Update .gitignore" -n || echo "No changes to commit"

    - git push -v -u --force "https://gitlab-ci-token:${CICD_ROBOT}@gitlab.com/Solaki/php_unit.git" HEAD:refs/heads/preprod
  when: on_success
  only:
    - dev

deploy_preprod:
  image: alpine:latest
  stage: deploy_preprod
  before_script:
    - apk add --no-cache lftp openssh-client
  script:
    - echo "Deploy en cours..."
    - git clone --depth 1 --branch preprod $CI_REPOSITORY_URL main
    - cd main
    - git clean -fdx
    - rm -rf .git .gitignore .gitlab-ci.yml README.md
    - lftp -d -c "set sftp:auto-confirm yes; set net:max-retries 3; open -u \"$SFTP_USER\",\"$SFTP_PASSWORD\" sftp://$SFTP_HOST:$SFTP_PORT; mirror --delete --verbose --reverse ./ /www/preprod"
  when: manual
  only:
    - preprod

push_prod:
  image: alpine:latest
  stage: push_prod
  before_script:
    - apk add --no-cache git
  script:
    - echo "Push en cours..."
    - git config --global user.name "CI-CD Robot V2"
    - git config --global user.email "robot.terminator@gmail.com"
    - git push -v -u --force "https://gitlab-ci-token:${CICD_ROBOTV2}@gitlab.com/Solaki/php_unit.git" HEAD:refs/heads/main
  when: on_success
  only:
    - preprod

deploy_prod:
  image: alpine:latest
  stage: deploy_prod
  before_script:
    - apk add --no-cache lftp openssh-client
  script:
    - echo "Deploy en cours..."
    - git clone --depth 1 --branch preprod $CI_REPOSITORY_URL main
    - cd main
    - git clean -fdx
    - rm -rf .git .gitignore .gitlab-ci.yml README.md
    - lftp -d -c "set sftp:auto-confirm yes; set net:max-retries 3; open -u \"$SFTP_USER\",\"$SFTP_PASSWORD\" sftp://$SFTP_HOST:$SFTP_PORT; mirror --delete --verbose --reverse ./ /www/prod"
  when: manual
  only:
    - main