image: php:8.3-cli

variables:
  DB_USER: runner
  DB_PASSWORD: password
  DB_HOST: mysql
  DB_PORT: 3306
  DB_NAME: phpunit
  DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=8.0.32&charset=utf8mb4"

services:
  - name: mysql:8.0
    alias: mysql
    variables:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: root

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y curl git unzip zip libzip-dev zlib1g-dev default-mysql-client
  - docker-php-ext-install zip pdo pdo_mysql
  - pecl install xdebug && docker-php-ext-enable xdebug
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - php -m | grep -E 'xml|mbstring'
  - apt-get install -y lftp

  - until mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" -e "SELECT 1"; do
      echo "Waiting for MySQL to be ready..."
      sleep 2;
    done
  - mysql -h "$DB_HOST" -u root -proot -e "DROP USER IF EXISTS '$DB_USER'@'%';"
  - mysql -h "$DB_HOST" -u root -proot -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';"
  - mysql -h "$DB_HOST" -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'%';"
  - mysql -h "$DB_HOST" -u root -proot -e "FLUSH PRIVILEGES;"

  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate --no-interaction --env=test

cache:
  paths:
    - vendor/
    - ~/.composer/cache

build:
  stage: build
  script:
    - echo "Build en cours..."
    - composer install --prefer-dist --no-progress --no-suggest --no-interaction

test:
  stage: test
  variables:
    XDEBUG_MODE: coverage
  script:
    - echo "Test en cours..."
    - composer grumphp